import type { Knex } from 'knex';

/*
 * Unidades FICTÍCIAS em Caruaru-PE, para a demo. Nomes, endereços e telefones
 * são inventados; as coordenadas caem nos bairros citados. A lotação inicial
 * varia de propósito: a UPA mais perto do centro (Boa Vista) começa lotada,
 * para a lista mostrar o aviso de "lotou" com a localização padrão.
 */
const UNITS = [
  // Rede pública (SUS)
  {
    name: 'UPA Vassoural',
    type: 'upa',
    network: 'public',
    address: 'Av. José Rodrigues de Jesus, 1200',
    neighborhood: 'Vassoural',
    lat: -8.2643,
    lng: -35.9852,
    occupancy: 'low',
    opening_hours: '24 h',
    phone: '8137210001',
  },
  {
    name: 'UPA Boa Vista',
    type: 'upa',
    network: 'public',
    address: 'Rua Marcílio Dias, 450',
    neighborhood: 'Boa Vista',
    lat: -8.2925,
    lng: -35.9618,
    occupancy: 'high',
    opening_hours: '24 h',
    phone: '8137210002',
  },
  {
    name: 'UPA Salgado',
    type: 'upa',
    network: 'public',
    address: 'Av. Oswaldo Cruz, 2300',
    neighborhood: 'Salgado',
    lat: -8.2701,
    lng: -35.9531,
    occupancy: 'medium',
    opening_hours: '24 h',
    phone: '8137210003',
  },
  {
    name: 'Hospital Municipal do Agreste',
    type: 'hospital',
    network: 'public',
    address: 'Av. Agamenon Magalhães, 800',
    neighborhood: 'Maurício de Nassau',
    lat: -8.2789,
    lng: -35.9702,
    occupancy: 'medium',
    opening_hours: '24 h',
    phone: '8137210004',
  },
  {
    name: 'UBS Centro',
    type: 'ubs',
    network: 'public',
    address: 'Rua Duque de Caxias, 120',
    neighborhood: 'Centro',
    lat: -8.2838,
    lng: -35.9761,
    occupancy: 'low',
    opening_hours: 'Seg a sex · 7h às 19h',
    phone: '8137210005',
  },
  {
    name: 'UBS Universitário',
    type: 'ubs',
    network: 'public',
    address: 'Rua Pedro Jordão, 300',
    neighborhood: 'Universitário',
    lat: -8.2992,
    lng: -35.9789,
    occupancy: 'medium',
    opening_hours: 'Seg a sex · 7h às 17h',
    phone: '8137210006',
  },
  {
    name: 'UBS Petrópolis',
    type: 'ubs',
    network: 'public',
    address: 'Rua São Sebastião, 85',
    neighborhood: 'Petrópolis',
    lat: -8.2734,
    lng: -35.9905,
    occupancy: 'low',
    opening_hours: 'Seg a sex · 7h às 17h',
    phone: '8137210007',
  },
  {
    name: 'UBS São Francisco',
    type: 'ubs',
    network: 'public',
    address: 'Rua Frei Caneca, 410',
    neighborhood: 'São Francisco',
    lat: -8.2866,
    lng: -35.9605,
    occupancy: 'high',
    opening_hours: 'Seg a sex · 7h às 17h',
    phone: '8137210008',
  },

  // Rede privada (plano)
  {
    name: 'Pronto-socorro Santa Clara',
    type: 'emergency_room',
    network: 'private',
    address: 'Av. Rui Barbosa, 1500',
    neighborhood: 'Maurício de Nassau',
    lat: -8.2812,
    lng: -35.9668,
    occupancy: 'low',
    opening_hours: '24 h',
    phone: '8137220001',
  },
  {
    name: 'Pronto-socorro Indianópolis',
    type: 'emergency_room',
    network: 'private',
    address: 'Rua Vigário Freire, 700',
    neighborhood: 'Indianópolis',
    lat: -8.2757,
    lng: -35.9612,
    occupancy: 'high',
    opening_hours: '24 h',
    phone: '8137220002',
  },
  {
    name: 'Hospital Esperança Agreste',
    type: 'hospital',
    network: 'private',
    address: 'Av. Portugal, 980',
    neighborhood: 'Universitário',
    lat: -8.2961,
    lng: -35.9735,
    occupancy: 'medium',
    opening_hours: '24 h',
    phone: '8137220003',
  },
  {
    name: 'Clínica Vida Plena',
    type: 'clinic',
    network: 'private',
    address: 'Rua Silva Jardim, 210',
    neighborhood: 'Centro',
    lat: -8.2851,
    lng: -35.9724,
    occupancy: 'low',
    opening_hours: 'Seg a sáb · 7h às 20h',
    phone: '8137220004',
  },
  {
    name: 'Teleconsulta do plano',
    type: 'telemedicine',
    network: 'private',
    address: null,
    neighborhood: null,
    lat: null,
    lng: null,
    occupancy: 'low',
    opening_hours: '24 h',
    phone: '08007220005',
  },
];

export async function seed(knex: Knex): Promise<void> {
  // Apaga em cascata os usuários vinculados.
  await knex('units').del();
  await knex('units').insert(UNITS);
}
